---
apiVersion: v1
kind: Service
metadata:
  name: blockscout-postgres
  labels:
    app: blockscout-postgres
spec:
  selector:
    app: blockscout-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-blockscout-postgres
  labels:
    app: blockscout-postgres
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: blockscout-postgres-pv
  storageClassName: gp2-ext4
  volumeMode: Filesystem

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockscout-postgres
  labels:
    app: blockscout-postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: blockscout-postgres
  template:
    metadata:
      labels:
        app: blockscout-postgres
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: eu-central-1a
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blockscout-postgres
                  key: POSTGRES_PASSWORD
          envFrom:
            - configMapRef:
                name: blockscout-postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: data-blockscout-postgres
