apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cb-basicauth
  namespace: default
spec:
  encryptedData:
    auth: AgCdYZ1pEjA716pCGtiZqasZCkam4WNnpqi3Bbkoe9IBNkXXvmoi0lvCosqGhDEHM4Rris/sa9NyhZPtOupTMQ7ameQmH6yKQOT91lKCNMZxiJz4uoTaUsnhNvg/ul9Mb19sBnpNl0QFTTg5hIRj1BE+nUCwSZFdrTd8w4hkzmxjGW4hkCjjNzGLKgfcPcoJawLR0ho2eagfuSEcGbsOOOOWhbl9OL5uBBZ8P9MaoKn9vwC2XyoT369d+2EnlFREAnE4pSjxbwgUNkLQ1XFoH7jSbwsZWCKOY5J3xQLkjGXdhPRWcltdQ/bogO2GhFVmfcSXmylFDJQZNtoHbwINk9uaekWx8z6CkAnaCA6WRC08LVza8zoMVBlwato3VY+Zwu5dEsbEvsydWQ1qOtOF/MRQiCLJwN2glCAaeqveDRGr40+GnGChhAF6RYjKKTENXOkqPtZJT4G0p7ibKm/LWndPyjHQgUPBhhdtWtKKsTI1u9RLF6UxhzDod6P/ZN1NqYK/+BWDEtJQ/zfb1dtuNWhYnoEWNT6ZKbfNJu/0OTEVbn2qxEbVhwbikQp+VA+OeCmrAmL7+8cd235R6LdWR1Lp5N43Alur5zvvydMvN0Gft0pxGi0FJGZS+aSiRNlmzJHBbm4aVC6atno0mItA5XhGGd6L4NLbNTJvESUsvPA3+PVnBNC1/TrUyOQcT/zjnG8kCakwsZ6onswJ9hTzYm7265uWriU1fQWM287gCTDdroG5mP+tAMQmFlhvQIsXiUIm
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cb-basicauth
      namespace: default

