---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-node-0
  labels:
    app: node
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: data-node-0
  storageClassName: gp2-ext4
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-node-2
  labels:
    app: node
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: data-node-2
  storageClassName: gp2-ext4
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-node-1
  labels:
    app: node
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: data-node-1
  storageClassName: gp2-ext4
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-node-0
  finalizers:
    - kubernetes.io/pv-protection
spec:
  capacity:
    storage: 10Gi
  awsElasticBlockStore:
    volumeID: aws://eu-central-1a/vol-028910ac51fd93b37
    fsType: ext4
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2-ext4
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - eu-central-1a
            - key: topology.kubernetes.io/region
              operator: In
              values:
                - eu-central-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-node-1
  finalizers:
    - kubernetes.io/pv-protection
spec:
  capacity:
    storage: 10Gi
  awsElasticBlockStore:
    volumeID: aws://eu-central-1b/vol-04404bb5660f21c3e
    fsType: ext4
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2-ext4
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - eu-central-1b
            - key: topology.kubernetes.io/region
              operator: In
              values:
                - eu-central-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-node-2
  finalizers:
    - kubernetes.io/pv-protection
spec:
  capacity:
    storage: 10Gi
  awsElasticBlockStore:
    volumeID: aws://eu-central-1a/vol-0f903bf93b087b720
    fsType: ext4
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2-ext4
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - eu-central-1a
            - key: topology.kubernetes.io/region
              operator: In
              values:
                - eu-central-1
