apiVersion: v1
kind: PersistentVolume
metadata:
  name: blockscout-postgres-pv
  labels:
    app: blockscout-postgres
  finalizers:
    - kubernetes.io/pv-protection
spec:
  storageClassName: gp2-ext4
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  awsElasticBlockStore:
    volumeID: vol-01bb27a592dd9deb4
    fsType: ext4
